config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5, maximum: 20 }
  validates :description, presence: true, length: { minimum: 15, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :articles, dependent: :destroy

  before_save do
    self.first_name = first_name.downcase.capitalize
    self.last_name = last_name.downcase.capitalize if !last_name.nil?
    self.email = email.downcase
  end

  validates :first_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :not_logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_logged_in?
    current_user.nil?
  end

  def user_required
    return unless not_logged_in?

    flash[:alert] = 'You must be logged in.'
    redirect_to login_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save
      flash[:notice] = 'Article Creation Successful'
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article Updation Successful.'
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end

    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    user = User.find_by(email: email)
    password = params[:session][:password]

    if !user.nil? && user.authenticate(password)
      session[:user_id] = user.id
      flash[:notice] = 'Logged In'
      redirect_to user
    else
      flash.now[:alert] = 'Incorrect Credentials'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged Out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Magazine #{@user.first_name}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new', staus: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Account Info Updated'
      redirect_to articles_path
    else
      render 'edit', staus: :unprocessable_entity
    end
  end

  def show
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "#{@user.first_name}'s account and all associated Articles are deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :password, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_logged_in?
    current_user.nil?
  end

  def user_required
    return if logged_in?

    flash[:alert] = 'You must be logged in.'
    redirect_to login_path
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_error.html.erb
<% if @article.errors.any? %>
  <h2>The following errors occured:-</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<br>
<%= link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<h3>Available Articles</h3>

<%= render 'shared/article' %>
<%= will_paginate @articles %>

app/views/articles/new.html.erb
<h2>Create Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h3><u><%= @article.title %></u></h3>
<p><%= @article.description %></p>
<br>
<p><strong>by: </strong><i><%= @article.user.first_name + ' ' + @article.user.last_name %></i><br>contact: <%= mail_to "#{@article.user.email}" %></p>

<% if @article.user_id == current_user.id %>
    <%= link_to 'Edit', edit_article_path(@article) %>
    <%= button_to 'Delete', article_path(@article), method: :delete %>
<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'HOME', root_path %> |
<%= link_to 'Available Articles', articles_path %> |
<%= link_to 'Registered Users', users_path %> |
<% if not_logged_in? %>
  <%= link_to 'Log in', login_path %> |
  <%= link_to 'Sign up!', signup_path %>

<% else %>
  <%= link_to 'Create Article', new_article_path %> |
  <%= link_to 'View Profile', user_path(current_user.id) %> |
  <%= link_to 'Edit Profile', edit_user_path(current_user.id) %> |
  <%= link_to 'Delete Profile', user_path(current_user.id), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Do you want to Delete Profile?"} %> |
  <%= link_to "LogOut -- #{current_user.first_name}", logout_path, method: :delete, data: {turbo_method: :delete, turbo_confirm: "Confirm LogOut?"} %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magazine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href = "https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <header>
    <%= render 'layouts/navbar' %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About Us:-</h2>
<p>This Magazine contains the articles associated with the user</p>

<p><strong>by:</strong> <%= link_to 'Anirudh Jain', "https://github.com/Anirudh-Jain" %></p>

<%= link_to 'HOME', '/' %>

app/views/pages/home.html.erb
<h1>Magazine</h1>

<p><strong><i> Find the Article you need </i></strong></p><br>

<%= link_to 'Available Articles', articles_path %>
<%= link_to 'About', about_path %>

app/views/shared/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Written by</th>
      <th colspan = 3>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user.first_name %></td>
        <% if !not_logged_in? && article.user_id == current_user.id %>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Delete', article_path(article), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
        <% else %>
          <td colspan = 3 ><%= link_to 'Show', article_path(article) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <h2>The following errors occured:-</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/error', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :first_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :first_name, class: "form-control shadow rounded", placeholder: "Enter first name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :last_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :last_name, class: "form-control shadow rounded", placeholder: "Enter last name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :age, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.number_field :age, class: "form-control shadow rounded", placeholder: "Enter your Age" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a Password" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label "Profile Picture", style: "display: block" %>
          <div class="col-10"> 
            <%= f.file_field :avatar %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '__Articles List__', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>Name of User</th>
      <th>Total Articles Written</th>
      <th colspan = 2>Actions</th>
      <th>Joined Magazine</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td> <%= link_to user.first_name, user %> </td>
      <td> <%= pluralize(user.articles.count, 'article') %> </td>
      <% if !not_logged_in? && user == current_user %>
        <td><%= link_to 'View Profile', user %></td>
        <td><%= link_to 'Edit Profile', edit_user_path(user) %></td>
      <% else %>
        <td colspan = 2><%= link_to 'View Profile', user %></td>
      <% end %>
      <td><%= time_ago_in_words(user.created_at) %> ago</td>
    </tr>
    <% end %>
  </tbody>

</table>

<div>
  <%= will_paginate @users, container: false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h2> User Profile</h1><br>
<img src = <%= @user.avatar %> />
<h5 class="text-center mt-4"><strong>Name: </strong><%= "#{@user.first_name} #{@user.last_name unless @user.last_name.nil?}" %></h3>
<h5 class="text-center mt-4"><strong>Age: </strong><%= @user.age %></h3>
<h5 class="text-center mt-4"><strong>Email: </strong><%= @user.email %></h3>

<% if !not_logged_in? && @user == current_user %>
    <div class = 'text-center mt-4'><%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-outline-info" %></div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'shared/article' %>
<%= will_paginate @articles %>